In [4]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)


[1 2 3 4 5]


In [8]:
a = np.array([[12,23],[12,34]])
print(a)

[[12 23]
 [12 34]]


In [5]:
#slicing in array
arr1 = np.array([1, 2, 3, 4, 5])
a = np.array([[12,23,243,43],[12,12,45,34]])
b = np.array([[12,23,243,87],
              [12,12,45,309],
              [12,43,54,65]])
print(arr1[0:2])
print(a[0:3,0:3])  #[r,c]
print(b[1:3,2:4])



[1 2]
[[ 12  23 243]
 [ 12  12  45]]
[[ 45 309]
 [ 54  65]]


In [6]:
a = np.array([[12,23,243,43],
              [12,12,45,34]])
print(np.shape(a))
print(np.size(a))
print(len(a))    #for length
print(a.dtype)      #for dimension
print(a.ndim)     #fpr datatype
print(a.astype(str))  #for converting dtype


(2, 4)
8
2
int64
2
[['12' '23' '243' '43']
 ['12' '12' '45' '34']]


In [17]:
arr1 = np.array([1, 2, 3, 4, 5,7])
arr2 = np.array([5, 2, 3, 4, 5,9])

print(np.concatenate((arr1, arr2)))  #for joining
print(np.split(arr1, 2))        #for splitting with sets
print(np.split(arr1, [1]))     #for slpiting with position
print(np.sort(arr2))     #for sorting
np.searchsorted(arr2,9)    #for searching





[1 2 3 4 5 7 5 2 3 4 5 9]
[array([1, 2, 3]), array([4, 5, 7])]
[array([1]), array([2, 3, 4, 5, 7])]
[2 3 4 5 5 9]


np.int64(5)

In [22]:
# agregate functions
arr1 = np.array([1, 2, 3, 4, 5,7])

print(np.sum(arr1))
print(np.size(arr1))
print(np.min(arr1))
print(np.max(arr1))





22
6
1
7
