In [2]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)


[1 2 3 4 5]


In [4]:
a = np.array([[12,23],[12,34]])
print(a)

[[12 23]
 [12 34]]


In [7]:
b = np.array([[11,23],[12,34]])
print(b+a)

[[23 46]
 [24 68]]


In [19]:
#slicing in array
arr1 = np.array([1, 2, 3, 4, 5])
a = np.array([[12,23,243,43],[12,12,45,34]])
b = np.array([[12,23,243,87],
              [12,12,45,309],
              [12,43,54,65]])
print(arr1[0:2])
print(a[0:3,0:3])  #[r,c]
print(b[1:3,2:4])



[1 2]
[[ 12  23 243]
 [ 12  12  45]]
[[ 45 309]
 [ 54  65]]
